import { jsxLocPlugin } from "@builder.io/vite-plugin-jsx-loc";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import fs from "node:fs";
import path from "path";
import { defineConfig } from "vite";


function swPrecachePlugin(): import("vite").Plugin {
  return {
    name: "sw-precache-manifest",
    apply: "build",
    closeBundle() {
      const outDir = path.resolve(import.meta.dirname, "dist/public");
      const assetsDir = path.resolve(outDir, "assets");

      if (!fs.existsSync(assetsDir)) return;

      // Collect all hashed assets from the build
      const assets = fs.readdirSync(assetsDir)
        .filter(f => /\.(js|css)$/.test(f))
        .map(f => ({
          url: `/assets/${f}`,
          revision: null, // Hash is in the filename
        }));

      // Add static assets that need revision tracking
      const CACHE_VERSION = Date.now().toString(36);
      const staticAssets = [
        { url: '/', revision: CACHE_VERSION },
        { url: '/offline.html', revision: CACHE_VERSION },
        { url: '/manifest.json', revision: CACHE_VERSION },
        { url: '/icons/icon-192x192.png', revision: CACHE_VERSION },
        { url: '/icons/icon-512x512.png', revision: CACHE_VERSION },
        { url: '/icons/apple-touch-icon.png', revision: CACHE_VERSION },
      ];

      const manifest = [...staticAssets, ...assets];

      // Write manifest injection script
      const manifestJs = `// Auto-generated by vite build — do not edit\nself.__WB_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`;
      fs.writeFileSync(path.resolve(outDir, "sw-manifest.js"), manifestJs);

      // Prepend import to sw.js in build output
      const swPath = path.resolve(outDir, "sw.js");
      if (fs.existsSync(swPath)) {
        const swContent = fs.readFileSync(swPath, "utf-8");
        fs.writeFileSync(swPath, `importScripts('./sw-manifest.js');\n${swContent}`);
      }

      console.log(`[sw-precache] Generated manifest with ${manifest.length} entries`);
    },
  };
}

const plugins = [react(), tailwindcss(), jsxLocPlugin(), swPrecachePlugin()];

export default defineConfig({
  plugins,
  resolve: {
    alias: [
      { find: "@", replacement: path.resolve(import.meta.dirname, "client", "src") },
      { find: "@shared", replacement: path.resolve(import.meta.dirname, "shared") },
      { find: "@assets", replacement: path.resolve(import.meta.dirname, "attached_assets") },
      // Exact match only — custom shiki shim with ~25 common languages instead of 232
      { find: /^shiki$/, replacement: path.resolve(import.meta.dirname, "client", "src", "lib", "shiki-shim.ts") },
    ],
  },
  envDir: path.resolve(import.meta.dirname),
  root: path.resolve(import.meta.dirname, "client"),
  publicDir: path.resolve(import.meta.dirname, "client", "public"),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
    target: "es2020",
    cssMinify: "lightningcss",
    rollupOptions: {
      output: {
        manualChunks(id) {
          // Vendor: React core
          if (id.includes("node_modules/react/") || id.includes("node_modules/react-dom/")) {
            return "vendor-react";
          }
          // Vendor: UI library (Radix)
          if (id.includes("@radix-ui/")) {
            return "vendor-radix";
          }
          // Vendor: tRPC + TanStack Query
          if (id.includes("@trpc/") || id.includes("@tanstack/")) {
            return "vendor-data";
          }
          // Vendor: Lucide icons
          if (id.includes("lucide-react")) {
            return "vendor-icons";
          }
          // Mermaid (lazy loaded, large)
          if (id.includes("mermaid")) {
            return "vendor-mermaid";
          }
        },
      },
    },
  },
  server: {
    host: true,
    allowedHosts: [
      ".manuspre.computer",
      ".manus.computer",
      ".manus-asia.computer",
      ".manuscomputer.ai",
      ".manusvm.computer",
      "localhost",
      "127.0.0.1",
    ],
    fs: {
      strict: true,
      deny: ["**/.*"],
    },
  },
});
