CREATE TABLE `card_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`cardId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameKana` varchar(255),
	`company` varchar(255),
	`position` varchar(255),
	`department` varchar(255),
	`email` varchar(320),
	`phone` varchar(50),
	`mobile` varchar(50),
	`address` text,
	`website` varchar(500),
	`notes` text,
	`tags` json,
	`relationship` varchar(100),
	`meetingContext` text,
	`meetingDate` timestamp,
	`lastContactedAt` timestamp,
	`contactCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `card_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `card_scan_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`cardId` int,
	`source` enum('line','web','api') NOT NULL,
	`imageUrl` varchar(1000) NOT NULL,
	`imageKey` varchar(500),
	`detectedCardType` varchar(50),
	`extractedText` text,
	`extractedData` json,
	`confidence` int,
	`status` enum('pending','processing','completed','failed','registered') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`lineMessageId` varchar(255),
	`lineReplyToken` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `card_scan_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`cardType` varchar(50) NOT NULL,
	`title` varchar(255) NOT NULL,
	`frontImageUrl` varchar(1000),
	`frontImageKey` varchar(500),
	`backImageUrl` varchar(1000),
	`backImageKey` varchar(500),
	`extractedData` json,
	`manualData` json,
	`tags` json,
	`notes` text,
	`isFavorite` int NOT NULL DEFAULT 0,
	`isArchived` int NOT NULL DEFAULT 0,
	`ocrStatus` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`ocrError` text,
	`ocrCompletedAt` timestamp,
	`lineMessageId` varchar(255),
	`viewCount` int NOT NULL DEFAULT 0,
	`lastViewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cards_id` PRIMARY KEY(`id`)
);
